server:
  port: 8080      #puerto del gateway

eureka:
  client:
    fetch-registry: true          #debe obtener y mantener una copia local de Eureka
    register-with-eureka: true    #debe registrarse con el Eureka Server
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/      #url del Eureka Server

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true     #genera rutas automaticamente para cada servicio registrado en Eureka
      globalcors:           #configuracion global de CORS
        cors-configurations:
          '[/**]':          #aplica esta configuracion CORS a todas las rutas
            allowedOriginPatterns: "http://*"       #permite cualquier origen http
            allowedMethods:     #metodos http permitidos
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"     #permite cualquier encabezado
            allowCredentials: true
      routes:     #definicion explicita de rutas para el gateway
        - id: m1-price-service        #identificador de la ruta
          uri: lb://m1-price-service  #uri del servicio, lb:// indica que se usara el balanceador de carga
          predicates:
            - Path=/prices/**         #cualquier solicitud que comience con /prices/ se dirigira a este servicio
        - id: m2-group-discount-service
          uri: lb://m2-group-discount-service
          predicates:
            - Path=/group-discount/**
        - id: m3-cliente-frecuente-service
          uri: lb://m3-cliente-frecuente-service
          predicates:
            - Path=/visit-discount/**
        - id: m4-holiday-discount-service
          uri: lb://m4-holiday-discount-service
          predicates:
            - Path=/holiday-discount/**
        - id: m5-reservation-service
          uri: lb://m5-reservation-service
          predicates:
            - Path=/reservations/**
        - id: m6-rack-service
          uri: lb://m6-rack-service
          predicates:
            - Path=/rack/**
        - id: m7-report-service
          uri: lb://m7-report-service
          predicates:
            - Path=/reports/**