server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]': # Patrón de ruta global
            allowedOrigins:
              - http://127.0.0.1:62734 # La URL de tu Frontend
              - http://192.168.49.2:31010 # La IP del nodo y el NodePort del Frontend (si lo vas a exponer así)
              - http://localhost:8080 # Si corres el frontend en localhost:8080 en dev
              - http://localhost:5173 # Si tu frontend Vite usa el puerto 5173 por defecto en dev
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: m1-price-service
          uri: lb://m1-price-service
          predicates:
            - Path=/prices/**
        - id: m2-group-discount-service
          uri: lb://m2-group-discount-service
          predicates:
            - Path=/group-discount/**
        - id: m3-cliente-frecuente-service
          uri: lb://m3-cliente-frecuente-service
          predicates:
            - Path=/visit-discount/**
        - id: m4-holiday-discount-service
          uri: lb://m4-holiday-discount-service
          predicates:
            - Path=/holiday-discount/**
        - id: m5-reservation-service
          uri: lb://m5-reservation-service
          predicates:
            - Path=/reservations/**
        - id: m6-rack-service
          uri: lb://m6-rack-service
          predicates:
            - Path=/rack/**
        - id: m7-report-service
          uri: lb://m7-report-service
          predicates:
            - Path=/reports/**