apiVersion: apps/v1
kind: Deployment
metadata:
  name: m1-price-service-deployment
  labels:
    app: m1-price-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m1-price-service
  template:
    metadata:
      labels:
        app: m1-price-service
    spec:
      containers:
        - name: m1-price
          image: emirjr/m1-image
          ports:
            - containerPort: 8090
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_M1
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_M1
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_M1
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD