apiVersion: v1
kind: Service
metadata:
  name: m1-price-service      #nombre del Service
spec:
  selector:                   #selecciona los pods que tienen la etiqueta 'app: m1-price-service'
    app: m1-price-service     #debe coincidir con la etiqueta 'app' del deployment de m1-price-service
  ports:
    - protocol: TCP
      port: 8090              #puerto en el que m1-price-service escucha dentro del pod
      targetPort: 8090        #puerto del contenedor al que se redirigira el tráfico
  type: ClusterIP             #comunicacion interna (no expone afuera del cluster)