apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"m1-price-service"},"name":"m1-price-service-deployment","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"m1-price-service"}},"template":{"metadata":{"labels":{"app":"m1-price-service"}},"spec":{"containers":[{"env":[{"name":"SPRING_DATASOURCE_URL","value":"jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"},{"name":"SPRING_DATASOURCE_USERNAME","valueFrom":{"secretKeyRef":{"key":"DB_USER","name":"postgres-credentials"}}},{"name":"SPRING_DATASOURCE_PASSWORD","valueFrom":{"secretKeyRef":{"key":"DB_PASSWORD","name":"postgres-credentials"}}},{"name":"SPRING_DATASOURCE_DRIVER_CLASS_NAME","value":"org.postgresql.Driver"},{"name":"DB_HOST","valueFrom":{"configMapKeyRef":{"key":"DB_HOST_M1","name":"postgres-config-map"}}},{"name":"DB_PORT","valueFrom":{"configMapKeyRef":{"key":"DB_PORT_M1","name":"postgres-config-map"}}},{"name":"DB_NAME","valueFrom":{"configMapKeyRef":{"key":"DB_NAME_M1","name":"postgres-config-map"}}}],"image":"emirjr/m1-image","name":"m1-price","ports":[{"containerPort":8090}]}]}}}}
  creationTimestamp: "2025-06-06T16:12:17Z"
  generation: 1
  labels:
    app: m1-price-service
  name: m1-price-service-deployment
  namespace: default
  resourceVersion: "5806"
  uid: 5b7cc970-bec7-4df4-a5b8-1f27a22bc6d5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: m1-price-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: m1-price-service
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USER
              name: postgres-credentials
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: postgres-credentials
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          value: org.postgresql.Driver
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST_M1
              name: postgres-config-map
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT_M1
              name: postgres-config-map
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME_M1
              name: postgres-config-map
        image: emirjr/m1-image
        imagePullPolicy: Always
        name: m1-price
        ports:
        - containerPort: 8090
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-06-06T16:12:17Z"
    lastUpdateTime: "2025-06-06T16:12:29Z"
    message: ReplicaSet "m1-price-service-deployment-5c6c67c6b8" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-06-06T17:00:18Z"
    lastUpdateTime: "2025-06-06T17:00:18Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
