apiVersion: apps/v1
kind: Deployment
metadata:
  name: m2-group-discount-service-deployment
  labels:
    app: m2-group-discount-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m2-group-discount-service
  template:
    metadata:
      labels:
        app: m2-group-discount-service
    spec:
      containers:
        - name: m2-group-discount
          image: emirjr/m2-image
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_M2
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_M2
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_M2
---
apiVersion: v1
kind: Service
metadata:
  name: m2-group-discount-service-service # Nombre DNS para acceder a este servicio
  labels:
    app: m2-group-discount-service-service
spec:
  selector:
    app: m2-group-discount-service # Debe coincidir con el label 'app' de tu Deployment
  ports:
    - protocol: TCP
      port: 8090        # El puerto al que otros servicios acceden
      targetPort: 8090    # El puerto del contenedor
  type: ClusterIP      # O LoadBalancer si quieres acceso externo