apiVersion: v1
kind: Service
metadata:
  name: m2-group-discount-service         #nombre del Service
spec:
  selector:                               #selecciona los pods que tienen la etiqueta 'app: m2-group-discount-service'
    app: m2-group-discount-service        #debe coincidir con la etiqueta 'app' del deployment de m2-group-discount-service
  ports:
    - protocol: TCP
      port: 8090                          #puerto en el que m2-group-discount-service escuchara dentro del cluster
      targetPort: 8090                    #puerto del contenedor al que se redirigira el trafico
  type: ClusterIP                         #comunicacion interna (no expone afuera del cluster)