apiVersion: v1
kind: Service
metadata:
  name: m3-cliente-frecuente-service              #nombre del Service
spec:
  selector:                                       #selecciona los pods que tienen la etiqueta 'app: m3-cliente-frecuente-service'
    app: m3-cliente-frecuente-service             #debe coincidir con la etiqueta 'app' del deployment de m3-cliente-frecuente-service
  ports:
    - protocol: TCP
      port: 8090                                  #puerto en el que m3-cliente-frecuente-service escuchara dentro del cluster
      targetPort: 8090                            #puerto del contenedor al que se redirigira el trafico
  type: ClusterIP                                 #comunicacion interna (no expone afuera del cluster)