apiVersion: v1
kind: Service
metadata:
  name: m4-holiday-discount-service                #nombre del Service
spec:
  selector:                                        #selecciona los pods que tienen la etiqueta 'app: m4-holiday-discount-service'
    app: m4-holiday-discount-service               #debe coincidir con la etiqueta 'app' del deployment de m4-holiday-discount-service
  ports:
    - protocol: TCP
      port: 8090                                   #puerto en el que m4-holiday-discount-service escuchara dentro del cluster
      targetPort: 8090                             #puerto del contenedor al que se redirigira el trafico
  type: ClusterIP                                  #comunicacion interna (no expone afuera del cluster)