apiVersion: v1
kind: PersistentVolume
metadata:
  name: m5-reservation-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/m5-reservation-db-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m5-reservation-db-pvc
  labels:
    app: postgres
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m5-reservation-db-deployment
  labels:
    app: m5-reservation-db
    tier: database
spec:
  selector:
    matchLabels:
      app: m5-reservation-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: m5-reservation-db
        tier: database
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              value: m5_reservation_db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: m5-reservation-db-data
      volumes:
        - name: m5-reservation-db-data
          persistentVolumeClaim:
            claimName: m5-reservation-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: m5-reservation-db-service
  labels:
    app: m5-reservation-db
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: m5-reservation-db
    tier: database
  type: LoadBalancer