apiVersion: v1
kind: Service
metadata:
  name: m5-reservation-service                    #nombre del Service
spec:
  selector:                                       #selecciona los pods que tienen la etiqueta 'app: m5-reservation-service'
    app: m5-reservation-service                   #debe coincidir con la etiqueta 'app' del deployment de m5-reservation-service
  ports:
    - protocol: TCP
      port: 8090                                  #puerto en el que m5-reservation-service escuchara dentro del cluster
      targetPort: 8090                            #puerto del contenedor al que se redirigira el trafico
  type: ClusterIP                                 #comunicacion interna (no expone afuera del cluster)