apiVersion: apps/v1
kind: Deployment
metadata:
  name: m5-reservation-service-deployment
  labels:
    app: m5-reservation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m5-reservation-service
  template:
    metadata:
      labels:
        app: m5-reservation-service
    spec:
      containers:
        - name: m5-reservation
          image: emirjr/m5-image
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_M5
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_M5
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_M5