apiVersion: apps/v1
kind: Deployment
metadata:
  name: m6-rack-service-deployment
  labels:
    app: m6-rack-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m6-rack-service
  template:
    metadata:
      labels:
        app: m6-rack-service
    spec:
      containers:
        - name: m6-rack
          image: emirjr/m6-image
          ports:
            - containerPort: 8090