apiVersion: v1
kind: Service
metadata:
  name: m6-rack-service                          #nombre del Service
spec:
  selector:                                      #selecciona los pods que tienen la etiqueta 'app: m6-rack-service'
    app: m6-rack-service                         #debe coincidir con la etiqueta 'app' del deployment de m6-rack-service
  ports:
    - protocol: TCP
      port: 8090                                 #puerto en el que m6-rack-service escuchara dentro del cluster
      targetPort: 8090                           #puerto del contenedor al que se redirigira el trafico
  type: ClusterIP                                #comunicacion interna (no expone afuera del cluster)