apiVersion: v1
kind: PersistentVolume
metadata:
  name: m6-rack-service-db-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/m6-rack-service-db-data" # Asegúrate de que esta ruta exista en tu Minikube
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: m6-rack-service-db-pvc
  labels:
    app: postgres
    tier: database
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m6-rack-service-db-deployment
  labels:
    app: m6-rack-service-db
    tier: database
spec:
  selector:
    matchLabels:
      app: m6-rack-service-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: m6-rack-service-db
        tier: database
    spec:
      containers:
        - name: rack-db
          image: postgres
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              value: m6-rack-service-db # Nombre de la base de datos que se creará
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: m6-rack-service-db-data
      volumes:
        - name: m6-rack-service-db-data
          persistentVolumeClaim:
            claimName: m6-rack-service-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: m6-rack-service-db-service # Nombre del servicio para la base de datos
  labels:
    app: m6-rack-service-db
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: m6-rack-service-db
    tier: database
  type: ClusterIP