apiVersion: apps/v1
kind: Deployment
metadata:
  name: m7-report-service-deployment        #nombre para deployment dentro del cluster
  labels:
    app: m7-report-service                  #etiquetas que identifican el deployment
spec:
  replicas: 1                               #numero de replicas del pod que se desea mantener en ejecucion (pod)
  selector:
    matchLabels:
      app: m7-report-service                #solo gestionara pods que tengan la etiqueta 'app: m7-report-service'
  template:
    metadata:
      labels:
        app: m7-report-service              #etiquetas que se asignaran a los pods creados por este deployment
    spec:
      containers:
        - name: m7-report                   #nombre del contenedor dentro del pod
          image: emirjr/m7-imagen:v14       #imagen
          ports:
            - containerPort: 8090           #puerto en el que el contenedor escucha dentro del pod
---
apiVersion: v1
kind: Service
metadata:
  name: m7-report-service                   #nombre del servicio que permite acceder al deployment
  labels:
    app: m7-report-service                  #etiquetas que identifican el servicio
spec:
  ports:
    - port: 8090                            #puerto en el que el servicio escuchara dentro del cluster
      targetPort: 8090                      #puerto del contenedor al que se redirigira el trafico
      protocol: TCP
  selector:
    app: m7-report-service                  #selecciona los pods que tienen la etiqueta 'app: m7-report-service'
  type: ClusterIP                           #comunicacion interna (no expone afuera del cluster)