apiVersion: apps/v1
kind: Deployment
metadata:
  name: m7-report-service-deployment
  labels:
    app: m7-report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m7-report-service
  template:
    metadata:
      labels:
        app: m7-report-service
    spec:
      containers:
        - name: m7-report
          image: emirjr/m7-image
          ports:
            - containerPort: 8090
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_M7
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_M7
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_NAME_M7
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD