apiVersion: v1
kind: ConfigMap                                       #configmap para almacenar las variables de entorno de la base de datos
metadata:
  name: postgres-config-map                           #nombre del configmap
  labels:
    app: postgres-config-map                          #etiquetas que identifican el configmap
data:
  DB_HOST_M1: "m1-price-service-db-service"           #nombre del Service de la base de datos
  DB_PORT_M1: "5432"                                  #puerto de la base de datos
  DB_NAME_M1: "m1-price-service-db"                   #nombre de la base de datos
  DB_HOST_M2: "m2-group-discount-db-service"
  DB_PORT_M2: "5432"
  DB_NAME_M2: "m2-group-discount-db"
  DB_HOST_M3: "m3-cliente-frecuente-db-service"
  DB_PORT_M3: "5432"
  DB_NAME_M3: "m3-cliente-frecuente-db"
  DB_HOST_M4: "m4-holiday-discount-db-service"
  DB_PORT_M4: "5432"
  DB_NAME_M4: "m4-holiday-discount-db"
  DB_HOST_M5: "m5-reservation-db-service"
  DB_PORT_M5: "5432"
  DB_NAME_M5: "m5-reservation-db"
  DB_HOST_M6: "m6-rack-service-db-service"
  DB_PORT_M6: "5432"
  DB_NAME_M6: "m6-rack-service-db"