server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server-service # Importante: Usa el nombre del servicio de Kubernetes
    prefer-ip-address: false # Asegura que se use el hostname en lugar de la IP
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      default-zone: http://eureka-server-service:8761/eureka/