server:
  port: 8888      #puerto del config server

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EmirSilva/Pep2Tingeso.git   #repositorio de configuracion
          clone-on-start: true
          default-label: main   #rama por defecto
          search-paths:
            - config-data       #ruta donde se encuentran los archivos de configuracion
  application:
    name: config-server         #nombre de la aplicacion