server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EmirSilva/Pep2Tingeso.git
          clone-on-start: true
          default-label: main
          search-paths:
            - config-data
  application:
    name: config-server