server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/EmirSilva/Pep2Tingeso.git
          default-label: main
          search-paths: config-data
  application:
    name: config-service
